version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    #restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: beadando
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:8080:8080'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://db:3306/beadando?createDatabaseIfNotExist=true'
    depends_on:
      - db